name: event_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  syncfusion_flutter_calendar: ^20.4.38
  dropdown_button2: ^1.9.2
  carousel_slider: ^4.2.1
  http: ^0.13.5
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.5

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/